#!/bin/bash
#SBATCH --job-name=PreFRBLE
#SBATCH --mail-user=stefan.hackstein@hs.uni-hamburg.de
#SBATCH --partition=std
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=12:00:00
#SBATCH --mail-type=FAIL
#SBATCH --mail-type=END
#SBATCH --export=NONE
#SBATCH --output=/work/stuf315/PreFRBLE/log/FRB.out

source /sw/batch/init.sh
source /home/stuf315/.source_crpropa_new


cd /work/stuf315/PreFRBLE/IGM

ipython execute_MakeFarLikelihood.py


# end of SBATCH script
