root = '/work/stuf315/'
root_FRB = root + 'FRB/'
root_data = root + 'enzo/gas_plus_dm_'
root_data = root + 'MHD-models/clues/2018/'
root_rays = root_FRB + 'rays/'
root_skymaps = root_FRB+'skymaps/'
root_probabilities = root_FRB+'probabilities/'
